"""v3

Revision ID: 50cdff0720be
Revises: 9257f4ae2e36
Create Date: 2023-09-27 12:34:34.569665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cdff0720be'
down_revision = '9257f4ae2e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('modelagem_ameacas',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('modelagem_ameacas',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
